### ISSUE TITLE
Special characters not being escaped on `system` call

### ISSUE THREAD

**Issue by ernestorocha** [0xStabby/chatgpt-vim#6]
When running the command `gpt` and on the input prompt the phrase has some special character, for instance `'`, it breaks the `system` call of the plugin.

For example:

<img width="634" alt="image" src="https://user-images.githubusercontent.com/36022/225331661-25781db4-93ba-4d1a-90b6-c9a570ad4861.png">

This is caused by how the `system` call is made here https://github.com/0xStabby/chatgpt-vim/blob/master/plugin/chatgpt.vim#L10

So, we should escape the input string with `shellescape`, like this:
```
  let prompt = shellescape(input("Enter chatgpt prompt: "))
```

as described here: https://github.com/airblade/vim-system-escape/blob/master/README.md

And remove the single quote from `system` call:
Previous code:
```
    let output = system("echo '" . prompt . "' | openai complete - -t " . g:openaiToken)
```

New code:
```
    let output = system("echo " . prompt . " | openai complete - -t " . g:openaiToken)
```

So we can perform queries with special characters:

<img width="949" alt="image" src="https://user-images.githubusercontent.com/36022/225333160-120b7783-630b-420e-b55b-abca6a7b5eea.png">

PS: Great plugin by the way! :)

**Comment by 0xStabby** [comment]
Oh awesome! Thanks for the fix! This is an issue I was aware of but had not gotten around to figuring out a solution.

If you would like you can feel free to fork the repo and create a pull request with this update, I will pull it in. If not then I'll just throw the fix in myself. 

And thanks, glad you like it! :relaxed:

**Comment by 0xStabby** [comment]
Added, thanks again for the tip!
