### ISSUE TITLE
change the command names

### ISSUE THREAD

**Issue by OrionRandD** [0xStabby/chatgpt-vim#8]
Could you change the command names to:
gpt
gptFile
gptRun

or
chatGPT
chatGPTfile
chatGPTrun
etc...

The reason is that, it is annoying to uppercase the first letter (g) all the time when using it in (n)vim  :(

**Comment by 0xStabby** [comment]
Do you not use the mappings?

with the mappings you can just say `gpt`/`gpf`/`gpr` in normal mode to use them

**Comment by OrionRandD** [comment]
> Do you not use the mappings?
> 
> with the mappings you can just say `gpt`/`gpf`/`gpr` in normal mode to use them

Oh! Haven't tried them...
But, still, consider to changing the command names for the sake of command-mode.
Thx.

**Comment by 0xStabby** [comment]
Oh, I was just about to add this in. But I've gotten an error:

```
E183: User defined commands must start with an uppercase letter
```

So I will not be pulling this change in.

One thing I will have to do yet is change up the readme to make the mappings stand out more, as those are really the best way to use the plugin I'd say, much faster, no need to ever really write the
